### ISSUE TITLE
Slow downloads

### ISSUE THREAD

**Issue by Bimbam360** [noidexe/godot-version-manager#28] opened 2023-07-09 03:29 UTC
As the title suggests, just went to downloaded 4.1 and in the time it took to get to 3% I'd already gotten bored and downloaded it direct from the Godot website.

If this were transient I would chalk it up to chance, but I've had similar experiences throughout the last couple of RC releases.

Otherwise, love your work!

**Comment by noidexe** [comment] 2023-07-09 18:55
It's been happening to me to but this is unrelated to GVM. See this issue from the Godot repo : https://github.com/godotengine/godot-website/issues/348 

GVM downloads the files hosted at Tuxfamily. Tuxfamily has been working really well but it can be slow sometimes, and/or depending on your location. Now it seems to be better but if was pretty slow the last couple of days. It might be due to lots of people downloading all the 4.1 RCs. Godot has become a pretty popular open source project. 

The reason it's faster through the Godot website is because releases are hosted on Github. I could switch to Github as a download mirror but the problem is only releases are hosted there, while GVM allows you to download alphas, betas, RCs, etc. 

I'll close this for now. If the situation doesn't improve I'll see if I can modify GVM so it fetches releases from Github instead of Tuxfamily.

**Comment by noidexe** [comment] 2023-07-19 20:44
Will be fixed by #30

**Closed** 2023-08-13 05:34 UTC
Labels: enhancement
