### ISSUE TITLE
Update from inside the app

### ISSUE THREAD

**Issue by duianto** [noidexe/godot-version-manager#17] opened 2023-05-11 14:27 UTC
Would it be possible to update the Godot Version Manager from inside the app?

Maybe it could:
- Download the new version.
- Rename the current version to gvm_old, or the gvm_(previous version number)
- Extract the new version to the current executables directory
- Show a Restart button

**Comment by noidexe** [comment] 2023-05-11 14:50
Duplicate of #10 

Yes, it should be possible but I need to look into it. Linux might not have issue with it but windows does not allow you to overwrite an exe that's currently running. If renaming is ok then it might be possible. I have no idea about OSX since apps are basically a renamed zip file and it's the one complaining the most about security.

**Closed by noidexe** 2023-05-11 14:50 UTC
